# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    routing_loader: false
    body_listener: true
    format_listener:
        rules:
            - { path: ^/api, priorities: ['json'], fallback_format: json, prefer_extension: true}
#    param_fetcher_listener: true
#    view:
#        view_response_listener: 'force'
#        formats:
#            json: true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true

#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
