version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: komis_database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: komis_backend
      MYSQL_USER: admin
    ports:
      - "3306:3306"
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8100:80"
    volumes:
      - .:/var/www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: secret
