version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: komis_database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: komis_backend
      MYSQL_USER: admin
    ports:
      - "3306:3306"
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8100:80"
    volumes:
      - .:/var/www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: secret
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
